plugins: ["jekyll-include-cache", "jekyll-titles-from-headings"]
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
atom_feed:
  hide: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
logo: "/assets/images/vis2021cph_logo_rgb.svg"
header:
  teaser: "/assets/images/itu-atrium.jpg"
author:
  name: "Your Name"
  avatar: "/assets/images/ITU_logo_UK jpg.jpg"
  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "IEEE VIS in Copenhagen"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      header: true
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
