plugins: ["jekyll-include-cache", "jekyll-titles-from-headings"]
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
atom_feed:
  hide: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-61041493-4"
    anonymize_ip: true
